name: hue_api
description: A Dart client library for Philips Hue.
version: 0.8.0
homepage: https://github.com/rootasjey/hue_api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 intl: ^0.17.0
 http: ^0.13.1
 built_value: ^8.1.2
 built_collection: ^5.1.1

dev_dependencies:
  build_runner:
  built_value_generator: ^8.1.2
  test: ^1.17.12
  mockito: ^5.0.16
