name: hue_api
description: A Dart client library for Philips Hue.
version: 0.8.0
homepage: https://github.com/rootasjey/hue_api
author: Jérémie Corpinot <jeremie@rootasjey.dev>

environment:
  sdk: '>=2.6.1 <3.0.0'

dependencies:
 intl: ^0.17.0
 http: ^0.13.1
 built_value: ^8.0.4
 built_collection: ^5.0.0

dev_dependencies:
  build_runner:
  built_value_generator: ^8.0.4
  test: ^1.16.8
  mockito: ^5.0.2
